name: test
on: [push, pull_request, workflow_dispatch]

jobs:
  dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Puzzles Server
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /home/github/dev/GamesmanPuzzles
            echo "Pulling from GitHub ---------------------------------------------------"
            git pull
            echo "Checking and installing new dependencies ------------------------------"
            pip3 install -r requirements.txt
            pip3 install -e .
            echo "Starting the server ---------------------------------------------------"
            sudo systemctl restart gmp-dev.service
            sleep 5
            systemctl status gmp-dev.service
          host: nyc.cs.berkeley.edu
          port: 2222
          user: github
          key: ${{ secrets.KEY }}
  prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Puzzles Server
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /home/github/prod/GamesmanPuzzles
            echo "Pulling from GitHub ---------------------------------------------------"
            git pull
            echo "Checking and installing new dependencies ------------------------------"
            pip3 install -r requirements.txt
            pip3 install -e .
            echo "Starting the server ---------------------------------------------------"
            sudo systemctl restart gmp.service
            sleep 5
            systemctl status gmp.service
          host: nyc.cs.berkeley.edu
          port: 2222
          user: github
          key: ${{ secrets.KEY }}
